CREATE DATABASE DB_SERVICO_RH;

USE DB_SERVICO_RH;

CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
FUNCAO CHAR(255),
PRIMARY KEY (ID)
);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,FUNCAO)
VALUES("ERIKA" ,20, "DEVA");
INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,FUNCAO)
VALUES("ELISA MARIA" ,18,"DESIGNER");

SELECT * FROM TB_FUNCIONARIOS;